### ISSUE TITLE
[Get Data] Just changing the [Proxy status] from [NOT RUNNING] to [CHECK NETWORK].

### ISSUE THREAD

**Issue by 3g4m4d** [KD-MM2/ShadowHunter-saveFile-Editor#1]
-  Clicked [Get Data] won't change anything except saying CHECK NETWORK in the Proxy status
- Tried multiple time ends up with nothing, it's just changing the [Proxy status] from [NOT RUNNING] to [CHECK NETWORK]
- Did everything possible, with 3 different iPhones running both win&mac = same issue!

- Regarding;
_NOTE: Your PC must have network connection, correct date&time, firewall disabled. If you facing Failed to get tokens error, just remove the old mitmproxy cert profile and install it again at [mitm.it](mitm.it)_
YES, I did tried all possibility = same result

- mitm is working just fine, tested it and it works fine!
- Since the issue is not from the client side then it's definitely from the APP side!

**Comment by Quangcha** [comment]
i have the same problem

**Comment by KD-MM2** [comment]
CLOSED DUE TO NEW VERSION RELEASED.
